// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AsdadsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void asdads() {
    // Test name: asdads
    // Step # | name | target | value
    // 1 | open | https://www.actitime.com/ | 
    driver.get("https://www.actitime.com/");
    // 2 | setWindowSize | 1111x1040 | 
    driver.manage().window().setSize(new Dimension(1111, 1040));
    // 3 | runScript | window.scrollTo(0,7) | 
    js.executeScript("window.scrollTo(0,7)");
    // 4 | click | linkText=Try Free | 
    driver.findElement(By.linkText("Try Free")).click();
    // 5 | click | id=first-name | 
    driver.findElement(By.id("first-name")).click();
    // 6 | type | id=first-name | Kråkan
    driver.findElement(By.id("first-name")).sendKeys("Kråkan");
    // 7 | click | id=last-name | 
    driver.findElement(By.id("last-name")).click();
    // 8 | type | id=last-name | Karlsson
    driver.findElement(By.id("last-name")).sendKeys("Karlsson");
    // 9 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 10 | type | id=email | krakankarlsson@pinnar.asu.se
    driver.findElement(By.id("email")).sendKeys("krakankarlsson@pinnar.asu.se");
    // 11 | click | id=company | 
    driver.findElement(By.id("company")).click();
    // 12 | type | id=company | Kråksta
    driver.findElement(By.id("company")).sendKeys("Kråksta");
    // 13 | mouseOver | id=start-trial-submit | 
    {
      WebElement element = driver.findElement(By.id("start-trial-submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | click | id=start-trial-submit | 
    driver.findElement(By.id("start-trial-submit")).click();
    // 15 | runScript | window.scrollTo(0,1) | 
    js.executeScript("window.scrollTo(0,1)");
  }
}
